# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aYh098YHY0L64EJxfw1dBHYK0matPrIH
"""

print("hello woeld",end="  ---- don ")
print("hello rahul")



age=10

city='jaipur'

print( type(city))

# 123456

comny="regex"
year=2024
print(f"comny name is {comny} year is {year}")

username="aman"
msg = f"hello user {username}"
print(msg)
username="tushar"
print(msg)

