# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TE1HI5bmEZCbhRzj18_3IgbWzGLNL96E
"""

row=4
for i in range(1,row+1):
  for k in range(1,i+1):
     print(k,end=" ")
  print(" ")

row=1
for i in range(1,5):
  for k in range(i):
     print(row,end=" ")
     row=row+1
  print(" ")

letter=A
for i in range(1,5):
  for k in range(i):
     print(letter,end=" ")
     letter+=1
  print(" ")

units=100
if(units<=10):
  print(units*50)
elif(10<units<=30):
  print(10*50+(units-10)*20)
elif(30<units<=40):
  print(10*50+(20*20)+(units-30)*10)
elif(40<units<=100):
  print(10*50+20*20+10*10+(units-40)*5)

