# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zj9wye_ZCCBTNSchYSA4UjMer6-ZaMpp
"""

x=10
y=18
if(x>10 and y>18 ):
  print("valid")
  else:
    print("not valid")

x=15
y=116
if(x>10 and y>18 ):
   print("valid")
else:
    print("not valid")

x=10
y=15
z=20
if(x<y and x<z):
   print(" x is minimm")
elif(y<x and y<z):
  print("y is minimmmmm")
elif(z<x and z<y):
  print("z is minimmm")
else:
   print("equals")

x=
if(x<60):
  print("fail")
elif(60<=x<75):
  print("average")
elif(75<=x<85):
  print("good")
elif(85<=x<95):
  print("exelent")
else:
  print("brelent")

x=60
if(x%2==0 and x%3==0):
  print("divide by 6")
else:
  print("not divide by 6")

x=5
if(x==1):
  print("january")
elif(x==2):
  print("febury")
elif(x==3):
  print("march")
elif(x==4):
  print("april")
elif(x==5):
  print("may")
elif(x==6):
  print("june")
elif(x==7):
  print("july")
elif(x==8):
  print("august")
elif(x==9):
  print("september")
elif(x==10):
  print("october")
elif(x==11):
  print("november")
elif(x==12):
  print("december")
else:
  print("not found your code")

