# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xypPgXP4fDQxrDnqVDbrFFfpSmJbeyO8
"""

x = 10
print(x*50)

x=15
if(x<=10):
  print(x*50)
  x=10+y
if(10<x<=20):
  print(10*50+20*x)

state="RAJASTHAN"
state[0:-6]

for i in range(1,11):

 print(i,end=" ")

