# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10IUtPuD41q_lh7lhcwOvmMCC0Delp9Ml
"""

print("helo \nworld",end="---")
print("hey rahul ")

print("heloo","hey",sep= "+")

age=10

print(type(age))

address="""plot no-
city
state"""
print(address)

company="Regex"
year=2024
print("company name is" ,company} year is {year})

# prompt:

# This code has several syntax errors and logical issues. Here's the corrected code:

print("hello\nworld", end="---")
print("hey rahul")
print("hello", "hey", sep="+")
age = 10
print(type(age))
address = """plot no-
city
state"""
print(address)

company = "Regex"
year = 2024
print(f"Company name is {company} and year is {year}")

print(id(x))

y=x
print(id(y))

